### ISSUE TITLE
缺少文件，编译不了啊

### ISSUE THREAD

**Issue by dirtycold** [wangxkBug/qt-stl#1]
提示没有face.h 现在不能编译啊

**Comment by wangxinkuan** [comment]
已经解决了

**Comment by dirtycold** [comment]
...貌似还是不行，现在提示是找不到 arcball.h 和 arcball.cpp
是不是没有提交

**Comment by wangxinkuan** [comment]
arcball是用opengl虚拟鼠标球，理论上这种移动场景的办法是最好的。
但是这个项目我没有去用鼠标球，用了是另外的一个摄像机漫游的算法。
我已经把需要改的地方改了，删除了没有用到的arcball。

**Comment by dirtycold** [comment]
貌似ok了。谢谢！
